### ISSUE TITLE
구글 계정 연동 문제

### ISSUE THREAD

**Issue by KihongHeo** [Zeta611/easyword#14]
안녕하세요.

로그인을 안하고 사용할 때는 문제가 없는데요.
구글 로긴 이후에 몇번 새로고침을 하면 사이트에 더이상 접속이 안됩니다. 콘솔창을 열어보니 아래와 같은 오류가 뜨는데 혹시나 관련이 있을지 모르겠습니다.
![스크린샷 2024-04-11 오후 2 04 29](https://github.com/Zeta611/easyword/assets/1281633/ffecb051-27b9-4c4b-8e6e-9a9cdc34408c)

**Comment by Zeta611** [comment]
저에게는 발생한 적이 없는 문제인데요, 살펴보도록 하겠습니다.

**Comment by Zeta611** [comment]
커밋 5ceb0f3c747e2438368dd22e8c46a7cfaf4a8bfa 으로 해결이 된 것 같습니다. 브라우저를 새로고침하여 고쳐진 코드를 담은 버전을 사용해 보신 후, 같은 문제가 발생하면 다시 알려주세요.

**Comment by Zeta611** [comment]
이미 eb718b7dc949ee74eb1b6a2ff92a10eae8219c04 으로 해결이 되었던 것 같습니다.
