### ISSUE TITLE
분야 필터링

### ISSUE THREAD

**Issue by KihongHeo** [Zeta611/easyword#19]
안녕하세요.

분야 필터링을 선택하면, 아무 분야도 지정되지 않는 용어도 무조건 포함이 되네요.
그것들은 "지정되지 않은 분야"로 만들어 선택하게 하면 어떨까요?

**Comment by Zeta611** [comment]
안녕하세요, 해당 방식은 이광근 교수님께서 요구하셨던 부분입니다.
