### ISSUE TITLE
데이터 수정

### ISSUE THREAD

**Issue by KihongHeo** [Zeta611/easyword#20]
제가 회의때 정리하면서 오해가 있게 적은것 같은데요.
https://easyword.kr/jargon/WzEsICJwdWJsaWMiLCAiamFyZ29uIiwgIjAwMTRmNDkxLWE1YWMtNGE1My05M2NkLTAyMWU1MDBiNTYwOSJd

여기에 간이, 땜질, 땜빵이 모두 간이 설정, 땜질 설정, 땜빵 설정 입니다.

**Comment by Zeta611** [comment]
수정 완료하였습니다!
