### ISSUE TITLE
Ipad bug

### ISSUE THREAD

**Issue by kwangkeun** [Zeta611/easyword#9]
용어 카드 누르면 “앗!404” 가 뜬다.

**Comment by Zeta611** [comment]
@kwangkeun 혹시 아이패드 운영체제가 아주 예전 것인가요?

**Comment by kwangkeun** [comment]
오래된 os인데. 그 때문이라면.. 그렇게 민감하다니 아쉽다.

**Comment by Zeta611** [comment]
커밋 4fbacfb1c0d19536091f79bb8b4b5e302b594016 으로 해결되었습니다.
